quarkus:
  http:
    port: 8081
  generate-code:
    grpc:
      scan-for-proto: com.zhqn:common

  grpc:
    server:
      port: 9091
    clients:
      platform:
        host: localhost
        port: 9092

  configuration:
    build-time-mismatch-at-runtime: fail
shop:
  upload-path: d:/testupload