quarkus:
  http:
    port: 8082
    limits:
      max-body-size: 1000M
    host-enabled: true
    host: localhost
  generate-code:
    grpc:
      scan-for-proto: com.zhqn:common
  grpc:
    clients:
      shop:
        host: localhost
        port: 9091
      platform:
        host: localhost
        port: 9092
    server:
      host: localhost
      port: 9092
platform:
  upload-path: d:/testupload