quarkus:
  http:
    port: 8082
    limits:
      max-body-size: 1000M
    host-enabled: true
  generate-code:
    grpc:
      scan-for-proto: com.zhqn:common
  grpc:
    clients:
      shop:
        host: localhost
        port: 9091
      platform:
        port: 9092
        host: localhost
    server:
      port: 9092
  datasource:
    default:
      username: quarkus
      password: quarkus
      db-kind: mysql
      jdbc:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.48.135:32100/quarkus
        validation-query-sql: select 1

platform:
  upload-path: d:/testupload